apiVersion: v1
kind: Secret
metadata:
  name: mysql-passwd
  namespace: cfitech
data:
  passwd: UEBzc3cwcmQxMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: cfitech
data:
  cnf: |
    [mysqld]
    slow-query-log = 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: cfitech
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: optimised
                operator: In
                values:
                - memory
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - zone2
            weight: 100
      containers:
      - name: database
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-passwd
              key: passwd
        - name: MYSQL_CONFIGURATION
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: cnf
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cfitech
spec:
  type: NodePort
  ports:
  - name: sql
    port: 3306
    protocol: TCP
    targetPort: sql
  selector:
    app: mysql
